"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONTRACT_TAKER_FEE_PRECISION = exports.POINTS_LENGTH_MASK = exports.RESOLVERS_LENGTH_OFFSET = exports.RESOLVERS_LENGTH_MASK = exports.HAS_TAKING_FEE_FLAG = exports.FLAGS_LENGTH = exports.TAKER_FEE_RATIO_LENGTH = exports.TAKER_FEE_RECEIVER_LENGTH = exports.PRIVATE_AUCTION_DEADLINE_LENGTH = exports.ALLOWED_TIMESTAMP_LENGTH = exports.ADDRESS_LENGTH = exports.AUCTION_DELAY_LENGTH = exports.AUCTION_BUMP_LENGTH = void 0;
exports.AUCTION_BUMP_LENGTH = 6;
exports.AUCTION_DELAY_LENGTH = 4;
exports.ADDRESS_LENGTH = 40;
exports.ALLOWED_TIMESTAMP_LENGTH = 8;
exports.PRIVATE_AUCTION_DEADLINE_LENGTH = 8;
exports.TAKER_FEE_RECEIVER_LENGTH = 40;
exports.TAKER_FEE_RATIO_LENGTH = 24;
exports.FLAGS_LENGTH = 2;
exports.HAS_TAKING_FEE_FLAG = 0x80;
exports.RESOLVERS_LENGTH_MASK = 0x78;
exports.RESOLVERS_LENGTH_OFFSET = 3;
exports.POINTS_LENGTH_MASK = 0x07;
exports.CONTRACT_TAKER_FEE_PRECISION = 1e9;
//# sourceMappingURL=constants.js.map